name: ItemFlex
version: 1.0.0
main: me.ujun.ItemFlexPlugin
author: U_jun
api-version: '1.21'
commands:
  showitem:
    permission: itemflex.show
    usage: /showitem <inventory|enderchest|mainhand>
  seeitem:
    permission: itemflex.see
    usage: /seeitem <player> <inventory|enderchest|mainhand>
  reload-itemflex:
    permission: itemflex.reload
    usage: /reload-itemflex

permissions:
  itemflex.show:
    description: Allows use of /showitem
    default: true
  itemflex.see:
    description: Allows use of /seeitem
    default: true
  itemflex.reload:
    description: Allows use of /itemflex reload
    default: op