player_inventory_message: "§6%player%'s Inventory"
enderchest_message: "§5%player%'s EnderChest"
mainhand_message: "§a%player%'s MainHand"
showitem_message: "<%player%> §7[§r%inventory_message%§7]"
showitem:
  error: "§cusage: /showitem <InventoryType>"
  no_item: "§cno item to show!"
seeitem:
  no_player: "§cPlayer not found."
  no_item: "§cno item to see!"
  error: "§cusage: /seeitem <Player> <InventoryType>"
  shulkerbox_message: "%player%'s ShulkerBox"
reload_message: "§aReload Complete!"